### ISSUE TITLE
Undefined index link

### ISSUE THREAD

**Issue by gjb2048** [iandavidwild/moodle-block_completion_progress#1]
Hi Ian,
When adding a completion block on a course on Moodle 3.3 - 3.3.1+ (Build: 20170720) - 2017051501.02 with version 2016090500 of the block which states its for M2.7 upwards - I get 'Notice: Undefined index: link in F:\moodledev\moodle33\blocks\completion_progress\lib.php on line 397'.
Cheers,
Gareth

**Comment by gjb2048** [comment]
Code looks pointless:

````
        if (!empty($activity['link']) && (!empty($activity['available']) || $simple)) {
            $activity_details['link'] = $activity['link'];
        } else {
            $activity_details['link'];
        }
````

and could be:

````
        if (!empty($activity['link']) && (!empty($activity['available']) || $simple)) {
            $activity_details['link'] = $activity['link'];
        }
````

**Comment by iandavidwild** [comment]
Hi Gareth,

This should be:

```
if (!empty($activity['link']) && (!empty($activity['available']) || $simple)) {
            $activity_details['link'] = $activity['link'];
        } else {
            $activity_details['link'] = '';
        }
```

I've updated the code accordingly.

Thanks,

Ian.

**Comment by gjb2048** [comment]
Hi Ian,

But

`````
$activity_details['link'];
`````

Does not actually do anything!

And causes: Notice: Undefined index: link in F:\moodledev\moodle33\blocks\completion_progress\lib.php on line 397.

**Comment by gjb2048** [comment]
Ah, your comment is wrong but the commit is correct: https://github.com/iandavidwild/moodle-block_completion_progress/commit/a775e4a14ce175532b5a2daf2c371f5a88052a69.
